### Login test
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "okumuraven@gmail.com",
  "password": "Kingbeez@254"
}

###

### Get current user
GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiam9zZXJhdmVsaW51eEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Njk2OTgyMzEsImV4cCI6MTc2OTcwNTQzMX0.2Oe23A8mjVj06-479RGtJv4G98T6FKKebtLdeO_RLTw

###