### Login test
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "okumuraven@gmail.com",
  "password": "Kingbeez@254"
}

###

### Get current user
GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib2t1bXVyYXZlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzE2NjE1ODMsImV4cCI6MTc3MTY2ODc4M30.ZyL-g-Ooq6MxEDM7s7Hb5dHBrcer66KBgubcerOBubs

###
GET http://localhost:5000/api/projects