### Login test
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "okumuraven@gmail.com",
  "password": "Kingbeez@254"
}

###
GET http://localhost:5000/api/timeline

### Get current user
GET http://localhost:5000/api/auth/me
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib2t1bXVyYXZlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzIwMjg5OTgsImV4cCI6MTc3MjAzNjE5OH0.5UjQl7F8JWaxAX9HIaPa3uSD1PmZzNhvdPqWRqj02XY
GET http://localhost:5000/api/projects

###
GET http://localhost:5000/api/timeline


GET http://localhost:5000/api/timeline/:id

GET http://localhost:5000/api/timeline/by-provider/event?provider=...&provider_event_id=...