import React, { useState, useEffect } from 'react';
import { useAuth } from '../../hooks/useAuth';
import * as authAPI from '../../api/auth.api';
import styles from './Security.module.css';

export default function Security() {
  const { user, fetchUser } = useAuth();
  const [loading, setLoading] = useState(false);
  const [setupData, setSetupData] = useState(null);
  const [token, setToken] = useState('');
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');

  const handleInitSetup = async () => {
    setLoading(true);
    setError('');
    try {
      const data = await authAPI.setup2FA();
      setSetupData(data);
    } catch (err) {
      setError('Failed to initialize 2FA setup.');
    } finally {
      setLoading(false);
    }
  };

  const handleVerifyAndEnable = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      await authAPI.verifyAndEnable2FA(setupData.secret, token);
      setMessage('Two-Factor Authentication enabled successfully!');
      setSetupData(null);
      setToken('');
      fetchUser(); // Refresh user state to show 2FA as enabled
    } catch (err) {
      setError(err?.response?.data?.error || 'Verification failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleDisable = async () => {
    if (!window.confirm('Are you sure you want to disable 2FA? This will make your account less secure.')) return;
    setLoading(true);
    setError('');
    try {
      await authAPI.disable2FA();
      setMessage('Two-Factor Authentication has been disabled.');
      fetchUser();
    } catch (err) {
      setError('Failed to disable 2FA.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1 className={styles.title}>Security Settings</h1>
        <p className={styles.subtitle}>Manage your account protection and authentication methods.</p>
      </header>

      <div className={styles.section}>
        <div className={styles.sectionHeader}>
          <h2 className={styles.sectionTitle}>Two-Factor Authentication (TOTP)</h2>
          <div className={`${styles.badge} ${user?.two_factor_enabled ? styles.active : styles.inactive}`}>
            {user?.two_factor_enabled ? 'ENABLED' : 'DISABLED'}
          </div>
        </div>

        <p className={styles.description}>
          Add an extra layer of security to your account by requiring a 6-digit code from an authenticator app (like Google Authenticator or Authy) whenever you log in.
        </p>

        {!user?.two_factor_enabled && !setupData && (
          <button className={styles.actionBtn} onClick={handleInitSetup} disabled={loading}>
            ENABLE 2FA
          </button>
        )}

        {setupData && (
          <div className={styles.setupBox}>
            <h3 className={styles.setupTitle}>Setup Instructions</h3>
            <ol className={styles.steps}>
              <li>Scan the QR code below with your Authenticator app.</li>
              <li>Alternatively, enter this secret key manually: <code className={styles.secret}>{setupData.secret}</code></li>
              <li>Enter the 6-digit code generated by the app to verify.</li>
            </ol>

            <div className={styles.qrContainer}>
              <img src={setupData.qrCodeDataURL} alt="2FA QR Code" className={styles.qrCode} />
            </div>

            <form onSubmit={handleVerifyAndEnable} className={styles.verifyForm}>
              <input
                type="text"
                placeholder="000000"
                maxLength="6"
                value={token}
                onChange={(e) => setToken(e.target.value.replace(/\D/g, ''))}
                className={styles.tokenInput}
                required
              />
              <div className={styles.formActions}>
                <button type="submit" className={styles.verifyBtn} disabled={loading || token.length !== 6}>
                  {loading ? 'VERIFYING...' : 'VERIFY & ENABLE'}
                </button>
                <button type="button" className={styles.cancelBtn} onClick={() => setSetupData(null)}>
                  CANCEL
                </button>
              </div>
            </form>
          </div>
        )}

        {user?.two_factor_enabled && (
          <div className={styles.enabledBox}>
            <p className={styles.successText}>✓ 2FA is currently protecting your account.</p>
            <button className={styles.disableBtn} onClick={handleDisable} disabled={loading}>
              DISABLE 2FA
            </button>
          </div>
        )}

        {error && <div className={styles.errorMsg}>[ERROR]: {error}</div>}
        {message && <div className={styles.successMsg}>{message}</div>}
      </div>
    </div>
  );
}
